# Generated by Django 5.0.6 on 2024-05-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LUNCH_SYSTEM", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="day_of_week",
            field=models.TextField(),
        ),
    ]
