# Generated by Django 5.0.6 on 2024-05-14 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LUNCH_SYSTEM", "0002_alter_menu_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="day_of_week",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ]
            ),
        ),
    ]
